'use strict';
module.exports = {
  USER_ROLE: 'user',
  ADMIN_ROLE: 'admin',
  MODERATOR_ROLE: 'moderator',
  MIN_USERNAME_LENGTH: 3,
  MAX_USERNAME_LENGTH: 20,
  MIN_PASSWORD_LENGTH: 6,
  MIN_TOKEN_LENGTH: 10,
  TOKEN_LENGTH: 200,
  TOURIST_SITE_STATUS_WAITING_FOR_APPROVAL: 0,
  TOURIST_SITE_STATUS_APPROVED_FOR_RATING: 1,
  TOURIST_SITE_STATUS_APPROVED_FOR_VISITING: 2,
  ALL_TOURIST_SITES_TYPE: 0,
  OFFICIAL_TOURIST_SITES_TYPE: 1,
  UNOFFICIAL_TOURIST_SITES_TYPE: 2,
};
